name: Build ROES Utility

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build CSS
      run: npm run build:css
      
    - name: Decode certificate
      run: |
        echo "${{ secrets.WINDOWS_PFX_BASE64 }}" | base64 --decode > cert.pfx
      shell: bash
      
    - name: Build Windows app
      run: npm run make
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
      
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: dist/*.exe
        
    - name: Cleanup certificate
      if: always()
      run: rm -f cert.pfx
      shell: bash

  create-release:
    needs: [build-windows]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release v${{ github.run_number }}
        tag_name: v${{ github.run_number }}
        files: |
          windows-build/*.exe
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 